# Generated by Django 4.0.3 on 2022-03-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='unidade',
            fields=[
                ('cod_und', models.IntegerField(max_length=200, primary_key=True, serialize=False)),
                ('nome_und', models.CharField(max_length=300)),
            ],
        ),
    ]
