# Generated by Django 4.0.3 on 2022-03-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='cod_und',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
