# Generated by Django 4.0.1 on 2022-03-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lais', '0003_cidadao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidadao',
            name='sobre_nome',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
