# Generated by Django 4.0.3 on 2022-03-19 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lais', '0007_delete_user_cidadao_usuario_alter_cidadao_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cidadao',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='cidadao',
            name='cpf',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
