# Generated by Django 4.0.3 on 2022-03-19 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lais', '0008_remove_cidadao_usuario_alter_cidadao_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cidadao',
            name='id',
        ),
        migrations.AlterField(
            model_name='cidadao',
            name='cpf',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
