# Generated by Django 4.0.3 on 2022-03-21 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lais', '0012_alter_cidadao_cpf'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='unidade',
            new_name='agendados',
        ),
    ]
