# Generated by Django 4.0.3 on 2022-03-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lais', '0014_agendados_cpf_alter_agendados_cod_und'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendados',
            name='cpf',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
