# Generated by Django 4.0.3 on 2022-03-21 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lais', '0016_alter_cidadao_cpf'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='agendados',
            new_name='agendado',
        ),
    ]
