# Generated by Django 4.0.3 on 2022-03-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lais', '0017_rename_agendados_agendado'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendado',
            name='ag_data',
            field=models.DateField(auto_now=True),
        ),
    ]
