# Generated by Django 4.0.3 on 2022-03-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lais', '0018_agendado_ag_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendado',
            name='ag_data',
            field=models.DateField(),
        ),
    ]
