# Generated by Django 4.0.3 on 2022-03-21 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lais', '0020_alter_agendado_ag_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendado',
            name='cpf',
            field=models.IntegerField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
