# Generated by Django 4.0.3 on 2022-03-21 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lais', '0021_alter_agendado_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendado',
            name='cpf',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='agendado',
            name='nome_und',
            field=models.CharField(max_length=200),
        ),
    ]
