# Generated by Django 4.0.3 on 2022-03-25 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lais', '0022_alter_agendado_cpf_alter_agendado_nome_und'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendado',
            name='cpf',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
